logging:
    #path: ./logs
    path: /Users/admin/Logs
    file: geekhub
    config: "classpath:logback-spring.xml"
upload:
  path: images

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/geekbase?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: rootpass

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
            enable_lazy_load_no_trans: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
#    email:
#      host: smtp.gmail.com
#      port: 587
#      username: geekhub.owu@gmail.com
#      password: owuproj2018
grokonez:
  app:
    jwtSecret: jwtGrokonezSecretKey
    jwtExpiration: 86400