logging:
    #path: ./logs
    path: /data/local/tomcat/logs
    file: geekhub
    config: "classpath:logback-spring.xml"
upload:
  path: images

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/geekbase?createDatabaseIfNotExist=true
        username: root
        password: root

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
            enable_lazy_load_no_trans: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
grokonez:
  app:
    jwtSecret: jwtGrokonezSecretKey
    jwtExpiration: 86400